// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Push struct {
	ID           string
	Type         string
	Method       string
	Timestamp    int64
	Project      string
	RepoName     string
	Url          string
	Repo         string
	Branch       string
	Error        bool
	Blocked      bool
	AllowPush    bool
	Authorised   bool
	Canceled     bool
	Rejected     bool
	AutoApproved bool
	AutoRejected bool
	CommitFrom   string
	CommitTo     string
	PushUser     string
	Data         []byte
}

type Repo struct {
	ID           string
	Project      string
	Name         string
	Url          string
	CanPush      []string
	CanAuthorise []string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	Username    string
	Password    *string
	GitAccount  string
	Email       string
	Admin       bool
	OidcID      *string
	DisplayName *string
	Title       *string
}
