// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
)

const addUserCanAuthorise = `-- name: AddUserCanAuthorise :execrows
UPDATE repos SET can_authorise = array_append(can_authorise, LOWER($1))
WHERE id = $2 AND NOT (LOWER($1) = ANY(can_authorise))
`

type AddUserCanAuthoriseParams struct {
	Member string
	ID     string
}

func (q *Queries) AddUserCanAuthorise(ctx context.Context, arg AddUserCanAuthoriseParams) (int64, error) {
	result, err := q.db.Exec(ctx, addUserCanAuthorise, arg.Member, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addUserCanPush = `-- name: AddUserCanPush :execrows
UPDATE repos SET can_push = array_append(can_push, LOWER($1))
WHERE id = $2 AND NOT (LOWER($1) = ANY(can_push))
`

type AddUserCanPushParams struct {
	Member string
	ID     string
}

func (q *Queries) AddUserCanPush(ctx context.Context, arg AddUserCanPushParams) (int64, error) {
	result, err := q.db.Exec(ctx, addUserCanPush, arg.Member, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRepo = `-- name: CreateRepo :one

INSERT INTO repos (project, name, url, can_push, can_authorise)
VALUES ($1, LOWER($2), $3, $4, $5)
RETURNING id, project, name, url, can_push, can_authorise
`

type CreateRepoParams struct {
	Project      string
	Name         string
	Url          string
	CanPush      []string
	CanAuthorise []string
}

// Repos ---------------------------------------------------------------------
func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.Project,
		arg.Name,
		arg.Url,
		arg.CanPush,
		arg.CanAuthorise,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Name,
		&i.Url,
		&i.CanPush,
		&i.CanAuthorise,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec


INSERT INTO users (username, password, git_account, email, admin, oidc_id, display_name, title)
VALUES (LOWER($1), $2, $3, LOWER($4), $5, $6, $7, $8)
`

type CreateUserParams struct {
	Username    string
	Password    *string
	GitAccount  string
	Email       string
	Admin       bool
	OidcID      *string
	DisplayName *string
	Title       *string
}

// sqlc query definitions for git-proxy-go. Generated into ./sqlc by `sqlc
// generate` (see sqlc.yaml). The schema source is internal/db/migrations.
// Users ---------------------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.GitAccount,
		arg.Email,
		arg.Admin,
		arg.OidcID,
		arg.DisplayName,
		arg.Title,
	)
	return err
}

const deletePush = `-- name: DeletePush :exec
DELETE FROM pushes WHERE id = $1
`

func (q *Queries) DeletePush(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePush, id)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE username = LOWER($1)
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUser, username)
	return err
}

const findUser = `-- name: FindUser :one
SELECT username, password, git_account, email, admin, oidc_id, display_name, title FROM users WHERE username = LOWER($1)
`

func (q *Queries) FindUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.GitAccount,
		&i.Email,
		&i.Admin,
		&i.OidcID,
		&i.DisplayName,
		&i.Title,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT username, password, git_account, email, admin, oidc_id, display_name, title FROM users WHERE email = LOWER($1)
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.GitAccount,
		&i.Email,
		&i.Admin,
		&i.OidcID,
		&i.DisplayName,
		&i.Title,
	)
	return i, err
}

const findUserByOIDC = `-- name: FindUserByOIDC :one
SELECT username, password, git_account, email, admin, oidc_id, display_name, title FROM users WHERE oidc_id = $1
`

func (q *Queries) FindUserByOIDC(ctx context.Context, oidcID *string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByOIDC, oidcID)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.GitAccount,
		&i.Email,
		&i.Admin,
		&i.OidcID,
		&i.DisplayName,
		&i.Title,
	)
	return i, err
}

const getPush = `-- name: GetPush :one
SELECT data FROM pushes WHERE id = $1
`

func (q *Queries) GetPush(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPush, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getPushes = `-- name: GetPushes :many
SELECT data FROM pushes
WHERE ($1::text IS NULL OR type = $1)
  AND ($2::boolean IS NULL OR error = $2)
  AND ($3::boolean IS NULL OR blocked = $3)
  AND ($4::boolean IS NULL OR allow_push = $4)
  AND ($5::boolean IS NULL OR authorised = $5)
  AND ($6::boolean IS NULL OR canceled = $6)
  AND ($7::boolean IS NULL OR rejected = $7)
ORDER BY timestamp DESC
`

type GetPushesParams struct {
	Type       *string
	Error      *bool
	Blocked    *bool
	AllowPush  *bool
	Authorised *bool
	Canceled   *bool
	Rejected   *bool
}

func (q *Queries) GetPushes(ctx context.Context, arg GetPushesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getPushes,
		arg.Type,
		arg.Error,
		arg.Blocked,
		arg.AllowPush,
		arg.Authorised,
		arg.Canceled,
		arg.Rejected,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepo = `-- name: GetRepo :one
SELECT id, project, name, url, can_push, can_authorise FROM repos WHERE name = LOWER($1)
`

func (q *Queries) GetRepo(ctx context.Context, name string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepo, name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Name,
		&i.Url,
		&i.CanPush,
		&i.CanAuthorise,
	)
	return i, err
}

const getRepoById = `-- name: GetRepoById :one
SELECT id, project, name, url, can_push, can_authorise FROM repos WHERE id = $1
`

func (q *Queries) GetRepoById(ctx context.Context, id string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoById, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Name,
		&i.Url,
		&i.CanPush,
		&i.CanAuthorise,
	)
	return i, err
}

const getRepoByUrl = `-- name: GetRepoByUrl :one
SELECT id, project, name, url, can_push, can_authorise FROM repos WHERE url = $1
`

func (q *Queries) GetRepoByUrl(ctx context.Context, url string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByUrl, url)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Name,
		&i.Url,
		&i.CanPush,
		&i.CanAuthorise,
	)
	return i, err
}

const getRepos = `-- name: GetRepos :many
SELECT id, project, name, url, can_push, can_authorise FROM repos
WHERE ($1::text IS NULL OR name = LOWER($1))
  AND ($2::text IS NULL OR url = $2)
  AND ($3::text IS NULL OR project = $3)
ORDER BY name
`

type GetReposParams struct {
	Name    *string
	Url     *string
	Project *string
}

func (q *Queries) GetRepos(ctx context.Context, arg GetReposParams) ([]Repo, error) {
	rows, err := q.db.Query(ctx, getRepos, arg.Name, arg.Url, arg.Project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Name,
			&i.Url,
			&i.CanPush,
			&i.CanAuthorise,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsers = `-- name: GetUsers :many
SELECT username, password, git_account, email, admin, oidc_id, display_name, title FROM users
WHERE ($1::text IS NULL OR username = LOWER($1))
  AND ($2::text IS NULL OR email = LOWER($2))
ORDER BY username
`

type GetUsersParams struct {
	Username *string
	Email    *string
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Username, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Username,
			&i.Password,
			&i.GitAccount,
			&i.Email,
			&i.Admin,
			&i.OidcID,
			&i.DisplayName,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserCanAuthorise = `-- name: RemoveUserCanAuthorise :exec
UPDATE repos SET can_authorise = array_remove(can_authorise, LOWER($1)) WHERE id = $2
`

type RemoveUserCanAuthoriseParams struct {
	Member string
	ID     string
}

func (q *Queries) RemoveUserCanAuthorise(ctx context.Context, arg RemoveUserCanAuthoriseParams) error {
	_, err := q.db.Exec(ctx, removeUserCanAuthorise, arg.Member, arg.ID)
	return err
}

const removeUserCanPush = `-- name: RemoveUserCanPush :exec
UPDATE repos SET can_push = array_remove(can_push, LOWER($1)) WHERE id = $2
`

type RemoveUserCanPushParams struct {
	Member string
	ID     string
}

func (q *Queries) RemoveUserCanPush(ctx context.Context, arg RemoveUserCanPushParams) error {
	_, err := q.db.Exec(ctx, removeUserCanPush, arg.Member, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users SET
  password     = COALESCE($1, password),
  git_account  = COALESCE($2, git_account),
  email        = COALESCE(LOWER($3), email),
  admin        = COALESCE($4, admin),
  oidc_id      = COALESCE($5, oidc_id),
  display_name = COALESCE($6, display_name),
  title        = COALESCE($7, title)
WHERE username = LOWER($8)
`

type UpdateUserParams struct {
	Password    *string
	GitAccount  *string
	Email       *string
	Admin       *bool
	OidcID      *string
	DisplayName *string
	Title       *string
	Username    string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.Password,
		arg.GitAccount,
		arg.Email,
		arg.Admin,
		arg.OidcID,
		arg.DisplayName,
		arg.Title,
		arg.Username,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const writeAudit = `-- name: WriteAudit :exec

INSERT INTO pushes (
  id, type, method, timestamp, project, repo_name, url, repo, branch,
  error, blocked, allow_push, authorised, canceled, rejected,
  auto_approved, auto_rejected, commit_from, commit_to, push_user, data
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9,
  $10, $11, $12, $13, $14, $15,
  $16, $17, $18, $19, $20, $21
)
ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type, method = EXCLUDED.method, timestamp = EXCLUDED.timestamp,
  project = EXCLUDED.project, repo_name = EXCLUDED.repo_name, url = EXCLUDED.url,
  repo = EXCLUDED.repo, branch = EXCLUDED.branch, error = EXCLUDED.error,
  blocked = EXCLUDED.blocked, allow_push = EXCLUDED.allow_push,
  authorised = EXCLUDED.authorised, canceled = EXCLUDED.canceled,
  rejected = EXCLUDED.rejected, auto_approved = EXCLUDED.auto_approved,
  auto_rejected = EXCLUDED.auto_rejected, commit_from = EXCLUDED.commit_from,
  commit_to = EXCLUDED.commit_to, push_user = EXCLUDED.push_user, data = EXCLUDED.data
`

type WriteAuditParams struct {
	ID           string
	Type         string
	Method       string
	Timestamp    int64
	Project      string
	RepoName     string
	Url          string
	Repo         string
	Branch       string
	Error        bool
	Blocked      bool
	AllowPush    bool
	Authorised   bool
	Canceled     bool
	Rejected     bool
	AutoApproved bool
	AutoRejected bool
	CommitFrom   string
	CommitTo     string
	PushUser     string
	Data         []byte
}

// Pushes (also the audit trail) ---------------------------------------------
func (q *Queries) WriteAudit(ctx context.Context, arg WriteAuditParams) error {
	_, err := q.db.Exec(ctx, writeAudit,
		arg.ID,
		arg.Type,
		arg.Method,
		arg.Timestamp,
		arg.Project,
		arg.RepoName,
		arg.Url,
		arg.Repo,
		arg.Branch,
		arg.Error,
		arg.Blocked,
		arg.AllowPush,
		arg.Authorised,
		arg.Canceled,
		arg.Rejected,
		arg.AutoApproved,
		arg.AutoRejected,
		arg.CommitFrom,
		arg.CommitTo,
		arg.PushUser,
		arg.Data,
	)
	return err
}
