// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 GitProxy Contributors

// Package postgres is the pgx/v5-backed implementation of the db.Store
// interface (P2-3). Queries are generated by sqlc into the sqlc subpackage; the
// Store here adapts them to the domain types in internal/db and is the only
// place that knows the column<->document mapping for pushes.
package postgres

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/dcoric/git-proxy-go/internal/db"
	"github.com/dcoric/git-proxy-go/internal/db/postgres/sqlc"
)

// Store is the Postgres-backed db.Store.
type Store struct {
	pool *pgxpool.Pool
	q    *sqlc.Queries
}

// compile-time assertion that Store satisfies the db.Store contract.
var _ db.Store = (*Store)(nil)

// Connect opens a pgx pool for the given DSN, verifies connectivity and returns
// a ready Store.
func Connect(ctx context.Context, dsn string) (*Store, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("create pgx pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping postgres: %w", err)
	}
	return NewWithPool(pool), nil
}

// NewWithPool wraps an existing pool as a Store. Useful for tests that own the
// pool's lifecycle.
func NewWithPool(pool *pgxpool.Pool) *Store {
	return &Store{pool: pool, q: sqlc.New(pool)}
}

// Pool exposes the underlying pool (e.g. for the scs session store in P3-1).
func (s *Store) Pool() *pgxpool.Pool { return s.pool }

// Close releases the connection pool.
func (s *Store) Close() { s.pool.Close() }
